---
permalink: task_active_iq_replication.html 
sidebar: sidebar 
keywords: solidfire, active, iq, replication 
summary: Obtenga información sobre la página Replication en SolidFire Active IQ. 
---
= Replicación
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La página *Replication*, disponible en el panel lateral de un clúster seleccionado, proporciona información sobre pares de clústeres y pares de volúmenes.

Obtenga más información acerca de las páginas de parejas de clústeres y parejas de volúmenes:

* <<cluster_pairs,Parejas de clústeres>>
* <<volume_pairs,Parejas de volúmenes>>
* <<snapmirror_endpoints,Extremos de SnapMirror>>
* <<snapmirror_relationships,Relaciones de SnapMirror>>




== Parejas de clústeres

En la página *Replication* > *Cluster Pairs* de un clúster seleccionado, puede ver la siguiente información acerca de pares de clústeres.

[cols="30,70"]
|===
| Título | Descripción 


| ID de pareja de clústeres | El número de ID que se otorga cuando se creó la pareja de clústeres. 


| Nombre de clúster remoto | El nombre del clúster remoto de la pareja. 


| MVIP remota | La IP virtual de gestión del clúster remoto. 


| Replicando volúmenes | Representa la cantidad de volúmenes que se replican en el clúster emparejado. 


| Estado | Estado de la pareja de clústeres. 


| UUID | Identificador único universal. 
|===


== Parejas de volúmenes

En la página *replicación* > *pares de volúmenes* de un clúster seleccionado, puede ver la siguiente información acerca de pares de volúmenes.

[cols="30,70"]
|===
| Título | Descripción 


| ID del volumen | El número de ID que se indica cuando se creó el volumen. 


| ID de cuenta | El ID de la cuenta asignada al volumen. 


| Estado del volumen | El estado del volumen duplicado. 


| Modo de replicación | El tipo de modo seleccionado para la pareja de volúmenes. 


| Dirección  a| 
Indica la dirección de los datos del volumen:

* Source: Indica que los datos se escriben en un objetivo fuera del clúster.
* Target: Indica que los datos se escriben en el volumen local de un origen externo.




| Retraso asíncrono  a| 
El tiempo transcurrido desde que el volumen se sincronizó por última vez con el clúster remoto. Si el volumen no se empareja, esto es nulo.


NOTE: Un volumen de destino en el estado de replicación activa siempre tiene un retraso asíncrono de 0 (cero). Los volúmenes de destino tienen en cuenta los sistemas durante la replicación y asumen que el retraso asíncrono es preciso en todo momento.



| Clúster remoto | El nombre del clúster remoto en el que reside el volumen. 


| ID del volumen remoto | El ID de volumen del volumen en el clúster remoto. 
|===


== Extremos de SnapMirror

En la página *Replication* > *SnapMirror Endpoints* de un clúster seleccionado, puede ver la siguiente información sobre los extremos de SnapMirror.

[cols="30,70"]
|===
| Título | Descripción 


| ID de extremo | El número de identificación del punto final. 


| Nombre de clúster remoto | El nombre del clúster remoto de la pareja. 


| IP de gestión del clúster | Dirección IP de gestión del clúster. 


| IPS | El rango de direcciones IP de red virtual que se utiliza para la red virtual. 


| Relaciones | El número de relaciones configuradas para un extremo. 


| Estado | Se refiere a si el extremo está conectado o no. Tiene un valor de *conectado* o *desconectado*. 
|===


== Relaciones de SnapMirror

En la página *replicación* > *Relaciones de SnapMirror* de un clúster seleccionado, puede ver la siguiente información acerca de las relaciones de SnapMirror.

[cols="30,70"]
|===
| Título | Descripción 


| ID de extremo | El número de identificación del punto final. 


| Volumen de origen | El ID de volumen del origen. 


| Clúster de destino | El nombre del clúster de destino de la relación de SnapMirror. 


| Volumen de destino | El nombre del volumen de destino en la relación de SnapMirror. 


| Estado  a| 
El estado de la relación de reflejo. Puede tener tres valores posibles:

* Inicializado: El volumen de destino no está inicializado.
* SnapMirror: El volumen de destino se inicializa y está listo para recibir actualizaciones de SnapMirror.
* Broken-off: El volumen de destino está en estado de lectura/escritura y las snapshots están presentes.




| Estado  a| 
Si la relación es actualmente saludable, puede tener un valor de *saludable* o *poco saludable*.


NOTE: Cuando una actualización manual o programada falla o se cancela, o la última actualización programada se retrasa, puede resultar en un valor *incorrecto*. El campo *Detalles* que sigue el estado muestra el motivo del estado *poco saludable*.



| Tipo de relación  a| 
El tipo de relación de SnapMirror.


NOTE: En sistemas SolidFire, siempre está configurado en `extended_data_protection`. Los sistemas NetApp tienen otros tipos de relaciones válidas que no se aplican en el caso de los sistemas SolidFire.



| Estado  a| 
El estado del clúster:

* Healthy: El clúster no tiene errores críticos asociados.
* Offline: No se puede acceder al clúster. Seleccione el vínculo para ver el registro de errores.
* Error: Existen errores asociados con este clúster. Seleccione el vínculo para ver el registro de errores.




| Detalles | Información que ayuda a identificar la relación de SnapMirror. 
|===


== Obtenga más información

* https://www.netapp.com/support-and-training/documentation/["Documentación de productos de NetApp"^]
* https://docs.netapp.com/us-en/ontap/element-replication/index.html["Replicación entre software de NetApp Element y ONTAP"^]

